### ISSUE TITLE
Thinkpad X230 mobile broadband not working

### ISSUE THREAD

**Issue by Fatih20** [elementary/switchboard-plug-network#191]
I use a thinkpad x230 that has a WWAN module.
When the sim aren't installed, I have the mobile broadband option in the networking dropdown menu, but it can be toggled on for reason mentioned.

 I put in the sim in the sim card slot. Turn on the laptop on as normal. Now, the option can be toggled on, but it still shows the icon for not being connected to the internet. If I then go to the settings (the previous stuff is the dropdown menu at the top bar), I found that mobile broadband actually hasn't been toggled on (despite the opposite in the dropdown menu at the top bar). If I then try turning it on, it will just close down instantly. 

I can get a screen recording if you wanted to.

**Comment by davidmhewitt** [comment]
Please provide some debugging output from the debugger `gdb` by doing the following in terminal:

1. Install `gdb` if it is not already installed with `sudo apt install gdb`
2. Load System Settings (Switchboard) inside `gdb` with `gdb io.elementary.switchboard`
3. Now run this application by typing `run` and pressing enter.
4. Re-produce the crash by toggling mobile broadband on
5. Get more information by typing `backtrace` and pressing enter.
6. Please share the lines after (gdb) backtrace, those should provide useful information.

**Comment by Fatih20** [comment]
`gdb io.elementary.switchboard
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from io.elementary.switchboard...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/io.elementary.switchboard 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe4e6b700 (LWP 2471)]
[New Thread 0x7fffdffff700 (LWP 2472)]
[New Thread 0x7fffd7bd3700 (LWP 2473)]
[New Thread 0x7fffc6c39700 (LWP 2474)]
[New Thread 0x7fffc6438700 (LWP 2475)]
[Thread 0x7fffc6438700 (LWP 2475) exited]

(io.elementary.switchboard:2467): Gtk-WARNING **: 20:11:59.804: Can't set a parent on widget which has a parent

Thread 1 "io.elementary.s" received signal SIGSEGV, Segmentation fault.
0x00007fffc5a12d75 in ?? () from /usr/lib/x86_64-linux-gnu/switchboard/network/libnetworking.so
(gdb) backtrace
#0  0x00007fffc5a12d75 in  () at /usr/lib/x86_64-linux-gnu/switchboard/network/libnetworking.so
#1  0x00007ffff72d510d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff72e805e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff72f0715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff72f112f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff72d95c4 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff72dbb09 in g_object_notify_by_pspec () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff69dd52e in gtk_switch_set_active () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff69dd988 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff6a72632 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff72d510d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff72e805e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff72f0715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff72f112f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff45af9a7 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#15 0x00007ffff459b080 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#16 0x00007ffff7904d03 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff7904285 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff7904650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff7904962 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff6927a25 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x000055555555da6c in  ()
#22 0x00007ffff72d510d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff72e7de8 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff72f0715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff72f112f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
`
Here's the whole thing in case I did something wrong. This time, it didn't crash, it freezes for  bit and then I was forced to force quit by a pop-up dialog saying that it's not responding.

**Comment by vividhaditya** [comment]
It's a long time since 2019 since the problem is which has crept into Odin as well.
